- hosts: localhost
  gather_facts: no

  vars:
    application_directory: /tmp/application

  tasks:
    - name: Create application directory
      file:
        path: "{{ application_directory }}"
        state: directory
        mode: "0755"

    - name: Get latest git version
      git:
        repo: https://github.com/KlimentC/devops-programme.git
        dest: "{{ application_directory }}"
        version: main
        force: yes

    - name: Install dependencies
      pip:
        requirements: "{{ application_directory }}/requirements.txt"
        virtualenv: "{{ application_directory }}/venv"

    - name: Run unit tests
      ansible.legacy.command: "{{ application_directory }}/venv/bin/python -m unittest app_test.py"
      args:
        chdir: "{{ application_directory }}/app"
      register: test_result

    - name: Print test results
      debug:
        var: test_result.stdout_lines
