apiVersion: apps/v1
kind: Deployment
metadata:
  name: decemberhomework-deployment
  labels:
    app: decemberhomework
spec:
  replicas: 5
  selector:
    matchLabels:
      app: decemberhomework
  template:
    metadata:
      labels:
        app: decemberhomework
    spec:
      containers:
        - name: decemberhomework
          image: klimentchakarovski/decemberhomework:v1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: decemberhomework-service
spec:
  type: NodePort
  selector:
    app: decemberhomework
  ports:
    - port: 8085
      targetPort: 3000 
      nodePort: 30007 
