---
- name: This is the Ansible Build for the Docker using the secrets from Ansible Vault
  hosts: localhost
  gather_facts: false
  vars:
    image_name: "homework"
    image_tag: "ver8"
    listen_port: "8000"
    default_dir: "/mnt/e/Repos/devops-programme"
    socpath: "unix:///var/run/docker.sock"
    docker_repo: "klimentchakarovski"

  tasks:
    - name: Include Docker Hub credentials from Ansible Vault
      ansible.builtin.include_vars:
        file: vault.yml
        name: vault_credentials

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ vault_credentials.docker_hub_username }}"
        p#passwordd: "{{ vault_credentials.docker_hub_password }}"
        registry: docker.io

    - name: Installing the dependencies from requirements.txt
      pip:
        requirements: "requirements.txt"
        executable: "/usr/bin/pip3"
        chdir: "{{ default_dir }}"

    - name: Build Docker image from Dockerfile
      community.docker.docker_image:
        name: "{{ docker_repo }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "{{ default_dir }}"
        state: present
        docker_host: "{{ socpath }}"

    - name: Push Docker image to Docker Hub
      community.docker.docker_image:
        name: "{{ docker_repo }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: local
        push: true

    - name: Run the container from the image
      community.docker.docker_container:
        name: pythonAppRun
        image: "{{ docker_repo }}/{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "{{ listen_port }}:{{ listen_port }}"
        env:
          PORT: "{{ listen_port }}"
        detach: true
        docker_host: "{{ socpath }}"
