name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - practiceLecture #Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main #Trigger on pull requests that target the 'main' branch

jobs:
  EditorConfig:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  Pylintjob:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Setup python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check the code with pylit
        run: |
          cd app && pylint $(git ls-files '*.py')

  Python-black:
    name: Python Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./app"
