name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
            - practiceLecture #Trigger on push to the 'main' branch
    pull_request:
        branches:
            - main #Trigger on pull requests that target the 'main' branch

jobs:
    EditorConfig:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - uses: editorconfig-checker/action-editorconfig-checker@main
            - run: editorconfig-checker
