---
name: GitHub Actions Workflow Kliment Ch.

on:
  push:
    branches:
      - practiceLecture
  pull_request:
    branches:
      - main
  
jobs:
  ScanForSecrets:
    name: GitLeaks check for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches full history to allow scanning across all commits

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowlist-paths: |
            .github/workflows/ci-pipeline.yml
            ansible/dockerBPRV.yml
          args: |
            --redact
            --exit-code=2
            --report-format=sarif
            --report-path=results.sarif
            --log-level=debug
            --log-opts=--no-merges
            --first-parent
            ${GITHUB_BASE_REF}..${GITHUB_SHA}


  
  EditorConfig:
    name: Editor Config Check
    runs-on: ubuntu-latest
    needs: ScanForSecrets
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
  
  PylintJob:
    name: Pylint Check for Python code
    runs-on: ubuntu-latest
    needs: ScanForSecrets
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Pylint
        run: |
          cd app && pylint -d C0114,C0115,C0116 $(git ls-files '*.py')
  
  PythonBlackJob:
    name: Python Black Check
    runs-on: ubuntu-latest
    needs: ScanForSecrets
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Black
        run: pip install black
      - name: Run Black
        run: black --check .
  
  MarkdownLintJob:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    needs: ScanForSecrets
    steps:
      - uses: actions/checkout@v4
      - name: Install Markdown Lint
        run: npm install -g markdownlint-cli
      - name: Run Markdown Lint
        run: markdownlint **/*.md
  
  UnitTestSnyk:
    name: Unit Tests and Snyk Check
    runs-on: ubuntu-latest
    needs: [EditorConfig, PylintJob, PythonBlackJob, MarkdownLintJob]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt coverage

      - name: Run tests with coverage and generate report
        run: |
          coverage run -m unittest discover -s app -p "*.py"
          coverage xml -o coverage.xml

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=critical

      - name: List files in ./app directory
        run: ls -R

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.0
        with:
          args: >
            -Dsonar.organization=klimentc
            -Dsonar.projectKey=KlimentC_devops-programme
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
  
 
  DockerBuildAndPush:
    name: Docker Build, Scan with Trivy, and Push
    runs-on: ubuntu-latest
    needs: [UnitTestSnyk]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-app:${{ github.sha }}
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/my-docker-app:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"
      - name: Push Docker image
        if: success()
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-docker-app:${{ github.sha }}
  
